### ISSUE TITLE
Deploy to webjars for simpler usage from maven

### ISSUE THREAD

**Issue by chriswk** [finn-no/spaden#13]
http://www.webjars.org/contributing - I'll have a look and see if I can't get a maven pom configured so this can be done at release time from main repo.

**Comment by stigkj** [comment]
Maybe rename title as this also makes it easier for Gradle :-)

**Comment by sveisvei** [comment]
I (personally) think npm and maven is enough complexity, PR welcome thought.
Closing this as its been lying around for over a year.
