### ISSUE TITLE
Use autoprefixer

### ISSUE THREAD

**Issue by Andersos** [finn-no/spaden#19]
I see that we are hand writing vendor prefixes in our css. 
Will the pull request be accepted if I add a step in our gulp file to [auto add vendor prefixes](https://github.com/postcss/autoprefixer)?

It is unclear what browser versions Spaden aims to support. From http://finn-no.github.io/nettlesermatrisen/ it looks like we should support IE9 but not IE8. Is this correct?

**Comment by antidecaf** [comment]
No, we support both, at least to some degree. C grade support means functionality should work, but doesn't necessarily have to look awesome. As for vendor prefixes - we plan to start using a CSS preprocessor in the not too distant future, which will take care of that among other things. :)
