### ISSUE TITLE
buggy/hacky .file-upload-button

### ISSUE THREAD

**Issue by jestho** [finn-no/spaden#41]
`.file-upload-button` is a tad hacky and causes jump to top of page in Firefox.

Since this is basically a file input in disguise, I suggest changing the wrapping element from `<a>` to `<label>` or `<span>`.

Demo: http://codepen.io/jestho/pen/KdOZvR

**Comment by antidecaf** [comment]
Thanks for the heads up.
Added fix (label button styling) and updated the styleguide documentation of .file-upload-button
