### ISSUE TITLE
Incorrect example at styleguide.finn.no

### ISSUE THREAD

**Issue by Hammerstad** [finn-no/spaden#74]
Hi

I'm unsure if this is the correct place to post this issue, but your readme linked to a hosted version of this project at styleguide.finn.no.

I looked around, and discovered that the example for uppercase is incorrect: the paragraph has a class called `strikethrough` instead of `uppercase`. See the attached image.

![uppercase-strikethrough](https://cloud.githubusercontent.com/assets/725330/16443238/d1291278-3dd7-11e6-93f7-bf85c8c8b1b6.PNG)

**Comment by Skadefryd** [comment]
Ah thanks :) will fix
